name: 'Setup OpenEdge'
description: 'Setup OpenEdge environment'
inputs:
  version:
    description: 'OpenEdge version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get OpenEdge version
      id: get-oeversion
      uses: bfv/openedge-flatversion@49ecdca1670447fcf715c0b505607ec17dc59b62  # v1.2.1
      with:
        version: ${{ inputs.version }}

    - name: Version to env
      run: |
        echo "FLATVERSION=${{ steps.get-oeversion.outputs.flat-version }}" >> $GITHUB_ENV
        echo "OPENEDGE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "OPENEDGE_BASE_VERSION=${{ steps.get-oeversion.outputs.base-version }}" >> $GITHUB_ENV

    - name: Insert JDK version in Dockerfile
      run: |
        jdk=`jq -r ".jdk${FLATVERSION}" src/jdk-versions.json`
        echo JDK: $jdk
        sed -i "s/JDKVERSION/$jdk/g" src/Dockerfile
        echo download jdk from Dockerfile:
        cat src/Dockerfile | grep temurin

    - name: Download installer files
      run: |
        src/download-openedge.sh

    - name: Get response.ini
      run: |
        echo fetching response.ini/progress.cfg from secret RESPONSE_INI_${{env.FLATVERSION}}
        echo "${{ secrets[format('RESPONSE_INI_{0}', env.FLATVERSION)] }}" > src/response.ini
        echo "${{ secrets[format('PROGRESS_CFG_{0}', env.FLATVERSION)] }}" | base64 --decode > src/progress.cfg
        ls -l src