name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-22.04
    
    # 12.8.3 was the latest version with a full installer. 12.8.4 is a patch release, which requires 
    # a base installation on top of which >= 12.8.4 is installed.
    strategy:
      matrix:
        version: [ 12.8.3, 12.8.6 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup OpenEdge
        uses: ./.github/actions/setup-openedge
        with:
          version: ${{ matrix.version }}

      - name: Get response.ini
        shell: bash
        run: |
          echo "${{ secrets[format('RESPONSE_INI_{0}', env.FLATVERSION)] }}" > response.ini
          echo "${{ secrets[format('PROGRESS_CFG_{0}', env.FLATVERSION)] }}" | base64 --decode > progress.cfg

      - name: Build docker image
        run: |
          docker build -f Dockerfile -t openedge-common:${{env.OPENEDGE_VERSION}} .

      